version: '3.9'

services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure

  celery:
    build: ./calculator
    container_name: celery
    restart: on-failure
    command: celery -A calculator worker -l info
    env_file:
      - ./.env
    volumes:
      - ./calculator/:/calculator/
    depends_on:
      - redis

  calculator:
    build: ./calculator
    container_name: calculator
    restart: on-failure
    command: sh -c "/calculator/entrypoint.sh"
    volumes:
      - ./calculator/:/calculator/:rw
      - calculator_data:/calculator/static
    ports:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

volumes:
  pgdata:
  calculator_data:
